name: chatbot
version: 0.1.5+1
description: ChatBot

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  flutter_riverpod: ^2.6.1

  http: ^1.2.2
  path_provider: ^2.1.4

  langchain: ^0.7.7+1
  langchain_openai: ^0.7.2+5

  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

  markdown: ^7.2.2
  flutter_markdown: ^0.7.4+1
  flutter_highlighter: ^0.1.1
  flutter_markdown_latex: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen
