name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master # 这个是测试的，正常不需要这么频繁
    tags:
      - '*' # 每次推送tag 的时候触发

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - name: Set up GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Automated build for version ${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}